# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create!(
  [
    {
      email: 'sakitayu@example.com',
      password: 'sakitayu',
      confirmed_at: Date.today,
      have_umbrella: true,
      area: '渋谷womb',
      name: 'さっきー',
      gender: '男',
      age: '34~40',
      introduction: 'さっきーです！よろしくお願いします！',
    },
    {
      email: 'tuborin@example.com',
      password: 'tuborin',
      confirmed_at: Date.today,
      have_umbrella: true,
      area: '渋谷駅',
      name: 'つぼりん ',
      gender: '男',
      age: '34~40',
      introduction: 'お疲れ様です。つぼりんです。もう恋なんてしないなんて〜言わないよ絶対〜 (c)JASRAC',
    },
    {
      email: 'kiyopii@example.com',
      password: 'kiyopii',
      confirmed_at: Date.today,
      have_umbrella: true,
      area: '神泉',
      name: 'きよp',
      gender: '男',
      age: '27~33',
      introduction: 'きよpだよ☆',
    },
    {
      email: 'zenchan@example.com',
      password: 'zenchan',
      confirmed_at: Date.today,
      have_umbrella: false,
      area: '笹塚',
      name: '善ちゃん',
      gender: '男',
      age: '20~26',
      introduction: 'しまんちゅうぬ宝〜(ここでポケットからウニを取り出す)',
    },
    {
      email: 'yoshiyuu@example.com',
      password: 'yoshiyuu',
      confirmed_at: Date.today,
      have_umbrella: false,
      area: '道玄坂のファミマ',
      name: 'よしむー',
      gender: '男',
      age: '20~26',
      introduction: '俺ガイル絶対見てください。面白いですよ。',
    },
    {
      email: 'anridayo@example.com',
      password: 'anridayo',
      confirmed_at: Date.today,
      have_umbrella: true,
      area: '渋谷セルリアンタワー',
      name: 'アンリ',
      gender: '女',
      age: '27~33',
      introduction: '趣味はサッカー観戦です！最近あんまり行ってないな〜',
    },
    {
      email: 'yukinee@example.com',
      password: 'yukinee',
      confirmed_at: Date.today,
      have_umbrella: false,
      area: '渋谷hub',
      name: 'ゆきねえ',
      gender: '女',
      age: '27~33',
      introduction: 'お酒大好き！肝臓は大切に！',
    },
    {
      email: 'yamachan@example.com',
      password: 'yamachan',
      confirmed_at: Date.today,
      have_umbrella: false,
      area: '渋谷マークシティ',
      name: '山ちゃん',
      gender: '男',
      age: '20~26',
      introduction: 'いまさっき傘をパクられました！悲しい！！',
    },
    {
      email: 'sugichan@example.com',
      password: 'sugichan',
      confirmed_at: Date.today,
      have_umbrella: true,
      area: '渋谷マークシティ',
      name: 'スギちゃん',
      gender: '男',
      age: '20~26',
      introduction: '男らしさを追い求めて早500年',
    },
    {
      email: 'ikkouikkou@example.com',
      password: 'ikkouikkou',
      confirmed_at: Date.today,
      have_umbrella: true,
      area: '渋谷109',
      name: 'いっこう',
      gender: 'どちらでもない',
      age: '48~60',
      introduction: 'やだもう〜どんだけ〜',
    },
    {
      email: 'tamutamu@example.com',
      password: 'tamutamu',
      confirmed_at: Date.today,
      have_umbrella: true,
      area: '神泉',
      name: 'たむたむ',
      gender: '女',
      age: '27~33',
      introduction: 'はわわ〜折りたたみ傘と間違えてパン生地伸ばす棒持ってきちゃった〜＞＜',
    },
    {
      email: 'kandasan@example.com',
      password: 'kandasan',
      confirmed_at: Date.today,
      have_umbrella: false,
      area: '渋谷センター街',
      name: 'かんちゃん',
      gender: '男',
      age: '34~40',
      introduction: 'かんちゃんです。趣味は音楽を聴くことかな。',
    },
    {
      email: 'stevejobs@example.com',
      password: 'stevejobs',
      confirmed_at: Date.today,
      have_umbrella: false,
      area: '渋谷ヒカリエ',
      name: 'ジョブズ',
      gender: '男',
      age: '48~60',
      introduction: 'think different',
    },
    {
      email: 'donaldtrump@example.com',
      password: 'donaldtrump',
      confirmed_at: Date.today,
      have_umbrella: true,
      area: '渋谷ハチ公前',
      name: 'トランプ大統領',
      gender: '男',
      age: '非公開',
      introduction: 'ぽきゎトランプ大統領(^_−)−☆',
    },
    {
      email: 'anpanman@example.com',
      password: 'anpanman',
      confirmed_at: Date.today,
      have_umbrella: false,
      area: '南青山',
      name: 'アンパンマン',
      gender: '男',
      age: '非公開',
      introduction: '雨に濡れて力が出ない〜',
    },
    {
      email: 'dokinchan@example.com',
      password: 'dokinchan',
      confirmed_at: Date.today,
      have_umbrella: true,
      area: '南青山',
      name: 'ドキンちゃん',
      gender: '女',
      age: '非公開',
      introduction: '(^o^)',
    },
    {
      email: 'tokuninaidesu@example.com',
      password: 'tokuninaidesu',
      confirmed_at: Date.today,
      have_umbrella: false,
      area: 'ヒカリエ',
      name: 'とっくん',
      gender: '女',
      age: '27~33',
      introduction: '特にないです',
    },
    {
      email: 'mochimochi@example.com',
      password: 'mochimochi',
      confirmed_at: Date.today,
      have_umbrella: true,
      area: '渋谷駅',
      name: 'もちこ',
      gender: '女',
      age: '27~33',
      introduction: 'よろしく！',
    },
    {
      email: 'godzilla@example.com',
      password: 'godzilla',
      confirmed_at: Date.today,
      have_umbrella: true,
      area: '表参道',
      name: 'ゴジさん',
      gender: 'どちらでもない',
      age: '非公開',
      introduction: '..........',
    },
    {
      email: 'peropero@example.com',
      password: 'peropero',
      confirmed_at: Date.today,
      have_umbrella: true,
      area: '原宿駅',
      name: 'ぺろぺろ先輩',
      gender: '男',
      age: '20~26',
      introduction: '＾＾',
    },
    {
      email: 'hasshii@example.com',
      password: 'hasshii',
      confirmed_at: Date.today,
      have_umbrella: true,
      area: '行徳',
      name: 'はっしー',
      gender: '男',
      age: '34~40',
      introduction: 'ファkjhfvkじゃhsdfgkjsがlg',
    },
    {
      email: 'konakona@example.com',
      password: 'konakona',
      confirmed_at: Date.today,
      have_umbrella: true,
      area: '秋葉原',
      name: 'こなた',
      gender: '女',
      age: '非公開',
      introduction: 'こなたです☆',
    },
    {
      email: 'sample_a@example.com',
      password: 'sample_a',
      confirmed_at: Date.today,
      have_umbrella: true,
      area: '渋谷駅',
      name: 'サンプルAくん',
      gender: '男',
      age: '20~26',
      introduction: '',
    },
    {
      email: 'sample_b@example.com',
      password: 'sample_b',
      confirmed_at: Date.today,
      have_umbrella: false,
      area: '渋谷109',
      name: 'サンプルBちゃん',
      gender: '女',
      age: '20~26',
      introduction: '',
    }
  ]
)